/**
 * Reports (canvas: Reports.dc.html). One row per succeeded scan with its snapshot hash and a
 * download menu (HTML / JSON / SARIF, generated by the engine's report writers from the stored
 * ScanResult). The report builder (templates, signing, schedules, destinations) comes later.
 */
import { useMemo } from 'react';
import { useSearchParams } from 'react-router';
import { ChevronDownIcon, DownloadIcon } from 'lucide-react';
import type { ReportFormat, ReportRow, RiskLevel } from '@server/api-types';
import { REPORT_FORMATS } from '@server/api-types';
import { api } from '@/api';
import { useAuth } from '@/auth';
import { DataTable, type ColumnDef } from '@/components/DataTable';
import { PageHeader } from '@/components/PageHeader';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { fmtNum, fmtTime } from '@/lib/cn';
import { cn } from '@/lib/utils';
import { useProject } from '@/project';
import { ComingSoon, ErrorAlert, LabeledSelect, SectionCard, shortHash } from './e-parts/ui';
import { usePaged } from './e-parts/usePaged';

const FORMAT_LABEL: Record<ReportFormat, string> = { html: 'HTML', json: 'JSON', sarif: 'SARIF' };
const FORMAT_HINT: Record<ReportFormat, string> = {
  html: 'Readable report for people',
  json: 'Full result (schemaVersion 1)',
  sarif: 'For GitHub code scanning',
};
const LEVELS = ['critical', 'high', 'medium', 'low'] as const;
const COUNT_STYLE: Record<RiskLevel, string> = {
  critical: 'text-level-critical font-semibold',
  high: 'text-level-high',
  medium: 'text-level-medium',
  low: 'text-muted-foreground',
};

function Downloads({ row }: { row: ReportRow }) {
  const what = `${row.project.name} snapshot ${row.scanId}`;
  const file = (f: ReportFormat) => `blastradius-${row.scanId}.${f}`;
  return (
    <span className="inline-flex">
      <Button asChild size="xs" variant="outline" className="rounded-r-none">
        <a href={api.reportUrl(row.scanId, 'html')} download={file('html')} aria-label={`Download HTML report for ${what}`}>
          <DownloadIcon />
          HTML
        </a>
      </Button>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button size="xs" variant="outline" className="rounded-l-none border-l-0 px-1" aria-label={`More download formats for ${what}`}>
            <ChevronDownIcon />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-56">
          <DropdownMenuLabel className="text-xs text-muted-foreground">Download report</DropdownMenuLabel>
          <DropdownMenuSeparator />
          {REPORT_FORMATS.map((f) => (
            <DropdownMenuItem key={f} asChild>
              <a href={api.reportUrl(row.scanId, f)} download={file(f)} aria-label={`Download ${FORMAT_LABEL[f]} report for ${what}`}>
                <DownloadIcon />
                <span className="flex flex-col">
                  <span className="font-medium">{FORMAT_LABEL[f]}</span>
                  <span className="text-xs text-muted-foreground">{FORMAT_HINT[f]}</span>
                </span>
              </a>
            </DropdownMenuItem>
          ))}
        </DropdownMenuContent>
      </DropdownMenu>
    </span>
  );
}

export default function Reports() {
  const { me, can } = useAuth();
  const { projects } = useProject();
  const [sp, setSp] = useSearchParams();
  const project = sp.get('project') ?? '';
  const list = usePaged((cursor, s) => api.reports({ ...(project ? { project } : {}), limit: 500, ...(cursor ? { cursor } : {}) }, s), [project]);
  const crumbs = [{ label: me?.org?.name ?? 'Organization', to: '/' }, { label: 'Reports' }];

  const columns = useMemo<ColumnDef<ReportRow, any>[]>(
    () => [
      { id: 'project', accessorFn: (r) => r.project.name, header: 'Project', cell: ({ getValue }) => <span className="font-mono font-medium">{getValue()}</span> },
      { id: 'scan', accessorFn: (r) => r.scanId, header: 'Snapshot', cell: ({ getValue }) => <span className="font-mono text-xs">{getValue()}</span> },
      { id: 'createdAt', accessorFn: (r) => r.createdAt, header: 'Scanned', cell: ({ getValue }) => <span className="font-mono text-xs">{fmtTime(getValue())}</span> },
      {
        id: 'counts',
        accessorFn: (r) => r.counts.critical * 1e6 + r.counts.high * 1e3 + r.counts.medium,
        header: 'Findings (C · H · M · L)',
        meta: { label: 'Findings' },
        cell: ({ row }) => (
          <span className="font-mono tabular-nums" aria-label={LEVELS.map((l) => `${row.original.counts[l]} ${l}`).join(', ')}>
            {LEVELS.map((l, i) => (
              <span key={l}>
                {i > 0 && <span className="text-muted-foreground"> · </span>}
                <span className={cn(row.original.counts[l] > 0 ? COUNT_STYLE[l] : 'text-muted-foreground')}>{row.original.counts[l]}</span>
              </span>
            ))}
          </span>
        ),
      },
      {
        id: 'sha256',
        accessorFn: (r) => r.sha256,
        header: 'SHA-256',
        enableSorting: false,
        cell: ({ getValue }) => (
          <Tooltip>
            <TooltipTrigger asChild>
              <span tabIndex={0} className="cursor-help rounded-sm font-mono text-xs text-muted-foreground outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50">
                {shortHash(getValue())}
              </span>
            </TooltipTrigger>
            <TooltipContent className="max-w-none font-mono">{getValue()}</TooltipContent>
          </Tooltip>
        ),
      },
      {
        id: 'downloads',
        header: 'Download',
        enableSorting: false,
        enableGlobalFilter: false,
        enableHiding: false,
        meta: { label: 'Download', align: 'right' },
        cell: ({ row }) => <Downloads row={row.original} />,
      },
    ],
    [],
  );

  return (
    <TooltipProvider>
      <PageHeader
        crumbs={crumbs}
        title="Reports"
        meta={list.loading && list.items.length === 0 ? undefined : `${fmtNum(list.total)} snapshot${list.total === 1 ? '' : 's'}`}
      >
        <LabeledSelect
          label="Project"
          value={project || 'all'}
          onValueChange={(v) => {
            const n = new URLSearchParams(sp);
            if (v && v !== 'all') n.set('project', v);
            else n.delete('project');
            setSp(n, { replace: true });
          }}
          options={[{ value: 'all', label: 'All projects' }, ...projects.map((p) => ({ value: p.id, label: p.name }))]}
          className="min-w-[180px]"
        />
      </PageHeader>
      <div className="flex flex-col gap-4 px-4 py-4">
        {list.error && list.items.length > 0 && <ErrorAlert>Could not load more reports: {list.error.message}</ErrorAlert>}
        <SectionCard
          title="History"
          description="Every succeeded scan is a frozen snapshot. Reports are generated from it, so they can be reproduced later; the SHA-256 is of the stored JSON result."
          contentClassName="flex"
        >
          {list.error && list.items.length === 0 ? (
            <div className="grow p-4">
              <ErrorAlert title="Could not load reports">
                {list.error.message}{' '}
                <Button type="button" variant="link" size="xs" className="h-auto p-0" onClick={list.reload}>
                  Retry
                </Button>
              </ErrorAlert>
            </div>
          ) : (
            <DataTable
              label="Report history"
              data={list.items}
              columns={columns}
              loading={list.loading && list.items.length === 0}
              getRowId={(r) => r.scanId}
              total={list.total}
              filterPlaceholder="Filter by project, snapshot or hash…"
              emptyTitle="No reports yet"
              emptyDescription="Reports appear here after a scan succeeds. Run a scan from a project's Scans page."
              toolbar={
                list.hasMore ? (
                  <Button type="button" size="sm" variant="outline" onClick={list.loadMore} disabled={list.loading}>
                    {list.loading ? 'Loading…' : 'Load more'}
                  </Button>
                ) : undefined
              }
            />
          )}
        </SectionCard>
        <SectionCard
          title={
            <>
              Report builder <ComingSoon />
            </>
          }
          description="Templates (audit evidence pack, executive summary, project risk, entity dossier, change log), PDF and CSV output, signing, schedules and delivery to GitHub release assets or webhooks."
          contentClassName="flex flex-col gap-3 px-4 py-3 text-[13px] text-muted-foreground"
        >
          <p>
            {can('build_reports') ? 'You will be able to build and sign reports here.' : 'Building and signing reports needs the "Build and sign reports" permission.'} Until then,
            download the HTML, JSON or SARIF report for any snapshot above.
          </p>
          <div className="flex flex-wrap gap-x-6 gap-y-2">
            {['Sign reports', 'Scheduled delivery'].map((l, i) => (
              <span key={l} className="inline-flex items-center gap-2">
                <Switch id={`rb-${i}`} disabled checked={false} aria-describedby="rb-soon" />
                <Label htmlFor={`rb-${i}`} className="font-normal text-muted-foreground">
                  {l}
                </Label>
              </span>
            ))}
            <span id="rb-soon" className="sr-only">
              Not available yet
            </span>
          </div>
        </SectionCard>
      </div>
    </TooltipProvider>
  );
}
