/**
 * Reports (canvas: Reports.dc.html). One row per succeeded scan with its snapshot hash and
 * HTML / JSON / SARIF downloads (generated by the engine's report writers from the stored
 * ScanResult). The report builder (templates, signing, schedules, destinations) comes later.
 */
import { useMemo } from 'react';
import { useSearchParams } from 'react-router';
import type { ReportFormat, ReportRow, RiskLevel } from '@server/api-types';
import { REPORT_FORMATS } from '@server/api-types';
import { api } from '@/api';
import { useAuth } from '@/auth';
import { ButtonAnchor, Button } from '@/components/Button';
import { DataTable, type ColumnDef } from '@/components/DataTable';
import { ErrorState, LoadingState } from '@/components/EmptyState';
import { PageHeader } from '@/components/PageHeader';
import { cn, fmtNum, fmtTime } from '@/lib/cn';
import { useProject } from '@/project';
import { ComingSoon, Card, InlineAlert, Select, shortHash } from './e-parts/ui';
import { usePaged } from './e-parts/usePaged';

const FORMAT_LABEL: Record<ReportFormat, string> = { html: 'HTML', json: 'JSON', sarif: 'SARIF' };
const COUNT_STYLE: Record<RiskLevel, string> = {
  critical: 'text-destructive',
  high: 'text-warning',
  medium: 'text-foreground',
  low: 'text-muted-foreground',
};

export default function Reports() {
  const { me, can } = useAuth();
  const { projects } = useProject();
  const [sp, setSp] = useSearchParams();
  const project = sp.get('project') ?? '';
  const list = usePaged((cursor, s) => api.reports({ ...(project ? { project } : {}), limit: 500, ...(cursor ? { cursor } : {}) }, s), [project]);
  const crumbs = [{ label: me?.org?.name ?? 'Organization', to: '/' }, { label: 'Reports' }];

  const columns = useMemo<ColumnDef<ReportRow, any>[]>(
    () => [
      { id: 'project', accessorFn: (r) => r.project.name, header: 'Project', cell: ({ getValue }) => <span className="font-mono font-medium">{getValue()}</span> },
      { id: 'scan', accessorFn: (r) => r.scanId, header: 'Snapshot', cell: ({ getValue }) => <span className="font-mono text-xs">{getValue()}</span> },
      { id: 'createdAt', accessorFn: (r) => r.createdAt, header: 'Scanned', cell: ({ getValue }) => <span className="font-mono text-xs">{fmtTime(getValue())}</span> },
      {
        id: 'counts',
        accessorFn: (r) => r.counts.critical * 1e6 + r.counts.high * 1e3 + r.counts.medium,
        header: 'Findings (C · H · M · L)',
        meta: { label: 'Findings' },
        cell: ({ row }) => (
          <span className="font-mono tabular-nums" aria-label={(['critical', 'high', 'medium', 'low'] as const).map((l) => `${row.original.counts[l]} ${l}`).join(', ')}>
            {(['critical', 'high', 'medium', 'low'] as const).map((l, i) => (
              <span key={l}>
                {i > 0 && <span className="text-muted-foreground"> · </span>}
                <span className={cn(row.original.counts[l] > 0 && COUNT_STYLE[l])}>{row.original.counts[l]}</span>
              </span>
            ))}
          </span>
        ),
      },
      {
        id: 'sha256',
        accessorFn: (r) => r.sha256,
        header: 'SHA-256',
        enableSorting: false,
        cell: ({ getValue }) => (
          <span className="font-mono text-xs text-muted-foreground" title={getValue()}>
            {shortHash(getValue())}
          </span>
        ),
      },
      {
        id: 'downloads',
        header: 'Download',
        enableSorting: false,
        enableGlobalFilter: false,
        meta: { label: 'Download' },
        cell: ({ row }) => (
          <span className="flex gap-1">
            {REPORT_FORMATS.map((f) => (
              <ButtonAnchor
                key={f}
                size="xs"
                variant="outline"
                href={api.reportUrl(row.original.scanId, f)}
                download={`blastradius-${row.original.scanId}.${f}`}
                aria-label={`Download ${FORMAT_LABEL[f]} report for ${row.original.project.name} snapshot ${row.original.scanId}`}
              >
                {FORMAT_LABEL[f]}
              </ButtonAnchor>
            ))}
          </span>
        ),
      },
    ],
    [],
  );

  return (
    <>
      <PageHeader
        crumbs={crumbs}
        title="Reports"
        meta={list.loading && list.items.length === 0 ? undefined : `${fmtNum(list.total)} snapshot${list.total === 1 ? '' : 's'}`}
      >
        <Select
          label="Project"
          value={project}
          onChange={(e) => {
            const n = new URLSearchParams(sp);
            if (e.target.value) n.set('project', e.target.value);
            else n.delete('project');
            setSp(n, { replace: true });
          }}
        >
          <option value="">All projects</option>
          {projects.map((p) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </Select>
      </PageHeader>
      <div className="flex flex-col gap-4 px-5 py-4">
        {list.error && list.items.length > 0 && <InlineAlert>Could not load more reports: {list.error.message}</InlineAlert>}
        <Card
          title="History"
          description="Every succeeded scan is a frozen snapshot. Reports are generated from it, so they can be reproduced later; the SHA-256 is of the stored JSON result."
          bodyClassName="flex"
        >
          {list.loading && list.items.length === 0 ? (
            <LoadingState label="Loading reports…" />
          ) : list.error && list.items.length === 0 ? (
            <div className="grow">
              <ErrorState error={list.error} onRetry={list.reload} />
            </div>
          ) : (
            <DataTable
              label="Report history"
              data={list.items}
              columns={columns}
              getRowId={(r) => r.scanId}
              total={list.total}
              filterPlaceholder="Filter by project, snapshot or hash…"
              emptyTitle="No reports yet"
              emptyDescription="Reports appear here after a scan succeeds. Run a scan from a project's Scans page."
              toolbar={
                list.hasMore ? (
                  <Button size="xs" variant="outline" onClick={list.loadMore} disabled={list.loading}>
                    {list.loading ? 'Loading…' : 'Load more'}
                  </Button>
                ) : undefined
              }
            />
          )}
        </Card>
        <Card
          title={
            <span className="flex items-center gap-2">
              Report builder <ComingSoon />
            </span>
          }
          description="Templates (audit evidence pack, executive summary, project risk, entity dossier, change log), PDF and CSV output, signing, schedules and delivery to GitHub release assets or webhooks."
          bodyClassName="px-4 py-3 text-[13px] text-muted-foreground"
        >
          {can('build_reports') ? 'You will be able to build and sign reports here.' : 'Building and signing reports needs the "Build and sign reports" permission.'} Until then, download the
          HTML, JSON or SARIF report for any snapshot above.
        </Card>
      </div>
    </>
  );
}
